# Generated by Django 5.2.1 on 2025-05-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('facebook', 'Facebook'), ('google', 'Google'), ('apple', 'Apple')], max_length=50),
        ),
    ]
