# Generated by Django 5.2.1 on 2025-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('facebook', 'Facebook'), ('google', 'Google'), ('apple', 'Apple')], max_length=20),
        ),
    ]
