# Generated by Django 5.1.6 on 2025-06-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_inventory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.order'),
        ),
    ]
